### ISSUE TITLE
Feature Request: Don't highlight nerdtree-git-plugin status flags

### ISSUE THREAD

**Issue by PhilRunninger** [tiagofumo/vim-nerdtree-syntax-highlight#5]
When vim-nerdtree-syntax-highlight and [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) are used at the same time, and `g:NERDTreeFileExtensionHighlightFullName` is set to `1`, the filename's highlighting overrides the git status flag's highlighting, as seen here.

![screen shot 2016-08-18 at 4 23 49 pm](https://cloud.githubusercontent.com/assets/5598066/17789445/35a9136a-6560-11e6-873a-23375aeedb84.png)

**Comment by PhilRunninger** [comment]
Pull request #4 implements this request, as shown below:

![screen shot 2016-08-18 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/5598066/17789505/78aa688a-6560-11e6-892d-4cd1ec64cf8a.png)

**Comment by tiagofumo** [comment]
There is a bug with the pull request. It disables the colors for vim-devicons. I am creating a fix for this and will upload when I finish. For now you can use the version you created, since it works for your particular setup. Thanks for contributing.

**Comment by tiagofumo** [comment]
I pushed a fix for this. I tested it and seem to work as expected in all scenarios, so I am closing this issue.  Take a look to see if it works for you. Thanks again for opening this issue :+1:

**Comment by PhilRunninger** [comment]
@tiagofumo , I noticed a couple of things while testing.

* I see that you used `\w` in the regular expression. This ignores some legal filename characters, such as hyphens and periods, causing only the last part of the filename to be highlighted.

<img width="384" alt="screen shot 2016-08-20 at 1 48 47 pm" src="https://cloud.githubusercontent.com/assets/5598066/17832917/895a185a-66dd-11e6-97a5-066e1c1be41b.png">

* When NERDTree is opened the first time, vim is complaining about the characters used for the group names in the s:X function. The offending groups are for the extensions that contain the characters `+`, `#`, or `.`. However, this doesn't appear to prevent the highlighting from occurring.

**Comment by tiagofumo** [comment]
I see, you are right. My bad. I pushed a fix. It seems to be working correctly now. :+1:

**Comment by PhilRunninger** [comment]
This looks good, now; however, I'm still getting errors when I open NERDTree **for the first time**. `s:X` is complaining about some of the group names, even with special characters being escaped. 

I was able to solve the problem by making the `exec "hi " . a:group...` statements run silently: `exec "silent hi " . a:group...`.

![screen shot 2016-08-22 at 10 34 54 am](https://cloud.githubusercontent.com/assets/5598066/17858807/34c61fc2-6855-11e6-9fe0-b35b3b1498af.png)
